version: "3"
services:
  pgloader-pg:
    image: dimitri/pgloader
    volumes: 
    - "./pgloader-config:/loader"
    command: pgloader  /loader/pg/pg.load
  postgres:
    image: postgres:9.6.11
    ports:
    - "5432:5432"
    environment:
    - "POSTGRES_PASSWORD:dalong"
  postgres2:
    image: postgres:9.6.11
    ports:
    - "5433:5432"
    environment:
    - "POSTGRES_PASSWORD:dalong"